### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "TJDGH3725@gmail.com",
  "password": "1234"
}


### 인증 페이지 요청

GET http://localhost:8080/foo
Content-Type: :application/json
Cookie: SESSION=fb3b18ea-02d9-4cc4-8222-d66f7fdf6a42